version: 2

models:
  - name: order_stg
    description: "A starter dbt model"
    columns:
      - name: orderid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: STATUSCD
        tests:
          - accepted_values:
              values: ['01', '02', '03']
