version: 2

models:
  - name: customerorders
    description: "A starter dbt model"
    columns:
      - name: CUSTOMERID
        description: "The primary key for this table"
        tests:
          - not_null